services:
  postgres:
    image: postgres:18
    container_name: library-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: library-redis
    restart: unless-stopped


  migrate:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: library-migrate

    command:
      - "-path=/app/migrations"
      - "-database=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=${DB_SSLMODE}"
      - "up"

    depends_on:
      postgres:
        condition: service_healthy


  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: library-api
    restart: unless-stopped

    env_file:
      - /opt/library-management/.env

    ports:
      - "${APP_PORT}:8080"

    depends_on:
      migrate:
        condition: service_completed_successfully


volumes:
  postgres_data: