# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:18
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: library_management_test
          ports:
            - 5432:5432
          options: >-
            --health-cmd="pg_isready -U postgres -d library_management_test"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.5'
        
    - name: Vet
      run: go vet ./...
      
    - name: Build
      run: go build -v ./...
      
    - name: Run migration
      run: |
        docker run --rm \
          --network host \
          -v ${{ github.workspace }}/migrations:/migrations \
          migrate/migrate \
          -path=/migrations \
          -database "postgres://postgres:root@localhost:5432/library_management_test?sslmode=disable" \
          up
    - name: Test
      run: go test -v ./internal... -count=1
